# Generated by Django 5.2.17 on 2026-08-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0002_remove_product_product_code'),
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cafe.product'),
        ),
    ]
