# Generated by Django 5.2.17 on 2026-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_orders_product_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='bill_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='gst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
