# Generated by Django 5.2.17 on 2026-08-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
    ]
