# Generated by Django 5.2.17 on 2026-09-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0002_remove_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
